#!/usr/bin/python
# -*- coding:utf-8 -*-

import argparse
import getopt
import sys
import subprocess


def usage():
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('Hardisk Label', nargs='?', help=':The label of \
                        specific hardisk (/dev/sda, etc.)')
    return parser.print_help()


# psgrep_tuple : command,keyword
def run_command(hd_label):
    command = "smartctl -H {0}".format(hd_label)
    output = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
    outputstring = output.communicate()[0]
    print_out(hd_label, outputstring)


def print_out(hd_label, outputstring):
    if outputstring.find('PASSED') is not -1:
        print "{0} PASSED".format(hd_label)
        sys.exit(0)
    elif outputstring.find('OK') is not -1:
        print "{0} PASSED".format(hd_label)
        sys.exit(0)
    elif outputstring.find('FAILED') is not -1:
        print "{0} FAILED".format(hd_label)
        sys.exit(2)
    else:
        print outputstring.split('\n')[3]
        sys.exit(3)


def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "h", ["help"])
    except getopt.GetoptError as err:
        print err
        usage()
        sys.exit(2)

    if len(args) < 1 or len(args) > 1:
        usage()
        sys.exit(2)

    if len(opts) is not 0:
        for o, a in opts:
            if o in ("-h", "--help"):
                usage()
                sys.exit(2)
            else:
                usage()
                sys.exit(2)

    hd_label = args[0]
    run_command(hd_label)


if __name__ == '__main__':
    main()
