#!/bin/bash

PROGNAME=`/usr/bin/basename $0`
PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`

. $PROGPATH/status.sh

if [ $# -eq 0 ]; then
  echo "ERROR - no service name specific"
  exit "${STATE_UNKNOWN}"
fi

__usage() {
  echo "Usage: $PROGNAME [-h] [service name]"
  echo "options:"
  echo " service name : service name of this node (Use the formal system service name)"
}

#Parse Parameters
while [ $# -gt 0 ]; do
  case "$1" in
    -h | --help)
      __usage
      exit $STATE_UNKNOWN
      ;;
    *)
      SERVICE=$1
      ;;
  esac
shift
done

if ! [[ "${SERVICE}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "UNKNOWN - service name not valid"
  exit "${STATE_UNKNOWN}"
fi

__upstart() {
  # status check for upstart service
  status "$1" 2>/dev/null | grep -q "start/"
}

__sysvinit() {
  # status check for sysvinit
  "/etc/init.d/$1" status >/dev/null 2>&1
}

if [ -f "/etc/init/${SERVICE}.conf" ]; then
  __upstart "${SERVICE}"
  RC=$?
elif [ -f "/etc/init.d/${SERVICE}" ]; then
  __sysvinit "${SERVICE}"
  RC=$?
else
  echo "UNKNOWN - Support upstart or SysVinit Only"
  exit "${STATE_UNKNOWN}"
fi

if [ "${RC}" -eq 0 ]; then
  echo "OK - service is running"
  exit "${STATE_OK}"
else
  echo "CRITICAL - service is not running"
  exit "${STATE_CRITICAL}"
fi
